### ISSUE TITLE
make printing model optional?

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#101]
Jeff@SEI asked me whether it's possible to suppress printing a model for a delta-sat case. @scungao, what do you think? I think it's better to make it optional and only show it when `--print-model` is on.

**Comment by zenna** [comment]
Yes it should be optional!

**Comment by soonhokong** [comment]
I can make this change this evening. What about the option name for this? Note that we already have `--model` option which outputs a delta-sat model to `.smt2.model` file.

**Comment by scungao** [comment]
Perhaps just let --model be both printing it and saving to the file.
