### ISSUE TITLE
btw how's performance on the Flyspeck benchmarks?

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#103]
Have we tested again?

**Comment by soonhokong** [comment]
Just triggered. I'll send you the result soon. Shouldn't take more than 3 days (5m timeout * 1000 instances).

**Comment by soonhokong** [comment]
So far IBEX partially implemented atan2 support, lacking derivative and gradient of atan2. As a result, we can't use `--polytope` option and we only show UNSAT for 30% of instances so far without using the option.

I just implemented them in https://github.com/dreal-deps/ibex-lib/commits/feat-exprdiff-atan2. I will test it and create a pull-request on the blessed repository of IBEX.

**Comment by soonhokong** [comment]
Pull request is created: https://github.com/ibex-team/ibex-lib/pull/133

**Comment by soonhokong** [comment]
Found another bug, reported it to IBEX team: https://github.com/ibex-team/ibex-lib/issues/134

**Comment by soonhokong** [comment]
IBEX team fixed a problem, and merged my commits. I'm running the Flyspeck benchmarks.

**Comment by soonhokong** [comment]
Move to #177
