### ISSUE TITLE
--theory_propagation and --short_sat

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#105]
It seems that something is wrong in `--theory_propagation` option and it interferes with `--short_sat` option. @nnarodytska, do you have any clue?

Test: [tests/nra/osmosis-hockey-ML4.smt2](https://github.com/dreal/dreal3/blob/master/src/tests/nra/osmosis-hockey-ML4.smt2)

## Theory Propagation = OFF / Short SAT = OFF
```
Number of Complete   Check = 7
Number of Incomplete Check = 2446
Number of Assert           = 6887
Number of Push             = 7079
Number of Pop              = 7079
Running time               = 2.862548 s
```

## Theory Propagation = OFF / Short SAT = ON
```
Number of Complete   Check = 1
Number of Incomplete Check = 292
Number of Assert           = 876
Number of Push             = 892
Number of Pop              = 892
Running time               = 0.468689 s
```

## Theory Propagation = ON / Short SAT = OFF
```
Number of Complete   Check = 33
Number of Incomplete Check = 3371
Number of Assert           = 9123
Number of Push             = 9847
Number of Pop              = 9847
Running time               = 4.133326 s
```

## Theory Propagation = ON / Short SAT = ON
```
Number of Complete   Check = 40
Number of Incomplete Check = 2765
Number of Assert           = 6754
Number of Push             = 7536
Number of Pop              = 7536
Running time               = 227.483779 s
```

**Comment by nnarodytska** [comment]
I will have a look now.

**Comment by soonhokong** [comment]
Thank you. 

I have a meeting with Ed from 1:30pm ~ 2:00pm today. I'll drop by the lab after that, just to check.

**Comment by nnarodytska** [comment]
Yep, see you soon!
