### ISSUE TITLE
The C API for pow has insufficient #arguments

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#109]
`pow` is a binary function, but:

```C
opensmt_expr     opensmt_mk_pow                    ( opensmt_context, opensmt_expr);
```

**Comment by soonhokong** [comment]
It's interesting that the definition actually took two arguments while its definition took one arg. Moreover, it didn't generate any compiler warning/errors so far..

**Comment by soonhokong** [comment]
Anyway, it should be fixed now.
