### ISSUE TITLE
uniform proof file

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#11]
On SAT cases, could you make the nra version produce the same format as dreal/dreal, when I give "--proof"? (No need to care about UNSAT for now, perhaps just return unsat in that file.) 

So that I don't need to change my parsing scheme when reading results from the two versions.

**Comment by soonhokong** [comment]
will do.

**Comment by soonhokong** [comment]
src/tests/nra/01.smt2.proof file for dReal2 and dReal3. Please ignore the different models which are due to the different numeric solvers that we are using.

dReal2
```
SAT with the following box:
              y : [-0.73792119606267, -0.7373937155412443];
              x : [2.399999999999968, 2.400781249999995]
```

dReal3
```
SAT with the following box:
	x : [2.59921875, 2.6];
	y : [-0.8568887533689489, -0.8564857564614976]
```
