### ISSUE TITLE
Binary min/max in dReach

### ISSUE THREAD

**Issue by kquine** [dreal/dreal3#113]
The min and max functions are available in `dReal`, but not supported by the `dReach` parser yet.

**Comment by soonhokong** [comment]
@kquine, now, `min`/`max` are available in jump, guard, init, and goal. It's still not available in the right-hand-side of ODEs. Do you need that as well?

**Comment by kquine** [comment]
No, Min/max are currently not needed for ODEs (and I guess that they are
not directly supported by CAPD).
Thank you!

On Tue, May 12, 2015 at 5:16 AM, Soonho Kong <notifications@github.com>
wrote:

> @kquine <https://github.com/kquine>, now, min/max are available in jump,
> guard, init, and goal. It's still not available in the right-hand-side of
> ODEs. Do you need that as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/113#issuecomment-101206301>.
>



-- 
Kyungmin Bae, Postdoctoral Fellow
School of Computer Science
Carnegie Mellon University

**Comment by soonhokong** [comment]
I see. Then I will keep this issue closed.

Yes, we need to check whether CAPD supports it or not.

>

-- 

Best,
Soonho
