### ISSUE TITLE
A new (simple) bug

### ISSUE THREAD

**Issue by kquine** [dreal/dreal3#119]
In the latest version, whenever running drh files,  the following error happens:
`can't open file: --short_sat (triggered at ...dreal3/src/opensmt/smtsolvers/SMTConfig.C, 482)`

**Comment by soonhokong** [comment]
It's related to the recent change which replaced GFLAGS with EzOptionParser. The new library sort-of enforces users to place a filename in the last position of command-line arguments. I'll figure out how to relax this condition.

**Comment by kquine** [comment]
Is there any way to run .drh file from dReach in the current version? The error msg shows up even with the default option.

**Comment by soonhokong** [comment]
I'm fixing it.. Allow me 5min.

**Comment by soonhokong** [comment]
@kquine, please try the latest version.

**Comment by soonhokong** [comment]
For the record, it's fixed by bb885157b95af45027a744ead67bb3f2267310e5.

**Comment by kquine** [comment]
It works. Thank you!

On Wed, May 13, 2015 at 7:36 PM, Soonho Kong <notifications@github.com>
wrote:

> For the record, it's fixed by bb88515
> <https://github.com/dreal/dreal3/commit/bb885157b95af45027a744ead67bb3f2267310e5>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/119#issuecomment-101849510>.
>



-- 
Kyungmin Bae, Postdoctoral Fellow
School of Computer Science
Carnegie Mellon University

**Comment by dzufferey** [comment]
@soonhokong is there a way to have dReal read from the standard input and give options at the same time ? dReal without any option starts reading from stdin. however, when there are some options it triggers the error about not being able to open the file.  Thanks.

**Comment by soonhokong** [comment]
@dzufferey, I'm fixing the option parser now. The feature will be available soon.

**Comment by soonhokong** [comment]
@dzufferey, 070d174 also fixes your problem as well. Please let me know if you still have the problem.

**Comment by dzufferey** [comment]
@soonhokong Thanks, that works.
