### ISSUE TITLE
Problem on dReach path generation

### ISSUE THREAD

**Issue by kquine** [dreal/dreal3#120]
There are some problem for multiple jump conditions between two modes,
the same as one in https://github.com/dreal/dreal/issues/68.

**Comment by soonhokong** [comment]
I think we didn't patch `dReach` in dReal3 when we resolved dreal/dreal#68. I'll pick it up in an hour and let you know.

**Comment by soonhokong** [comment]
Closed by 6f2280e0acd1a908600bef7480c004c08efb828c.

**Comment by kquine** [comment]
Each smt2 file contains a test code, such as
"====================

VarDecl Map===================={

beta: [-1.500000, 1.500000],

gL: [-1.500000, 1.500000],",...

"


Could you remove such test code fragment?

On Fri, May 15, 2015 at 11:00 PM, Soonho Kong <notifications@github.com>
wrote:

> Closed by 6f2280e
> <https://github.com/dreal/dreal3/commit/6f2280e0acd1a908600bef7480c004c08efb828c>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/120#issuecomment-102566712>.
>



-- 
Kyungmin Bae, Postdoctoral Fellow
School of Computer Science
Carnegie Mellon University

**Comment by soonhokong** [comment]
Removed by d60691281769f52def58e110f63c8f2b67806e31
