### ISSUE TITLE
'--readable-proof' prints predicate not  part of the input file

### ISSUE THREAD

**Issue by dzufferey** [dreal/dreal3#124]
Sometime dReal prints simplified version of the predicate in the proof, rather than the predicate in the input formula. I've only saw this happen in the first step of the proof.

example
-----------

command: `dReal --readable-proof test.smt2`

where `test.smt2` contains:
```
(set-option :print-success false)
(set-option :produce-models true)
(set-option :precision 0.01)
(set-logic QF_NRA)
(declare-fun t () Real)
(assert (>= t 0.0))
(assert (<= t 2.0))
(declare-fun x () Real)
(assert (>= x 0.0))
(assert (<= x 2.0))
(declare-fun y () Real)
(assert (>= y 0.0))
(assert (<= y 2.0))
(assert (and (and (not (< (+ (sin t) 0.05) x)) (not (< (+ x 0.05) (sin t))) (not (< (+ (cos t) 0.05) y)) (not (< (+ y 0.05) (cos t)))) (and (not (< (+ 1.3 0.05) (+ (^ x 2) (^ y 2)))) (not (< (+ (+ (^ x 2) (^ y 2)) 0.05) 1.3)))))
(check-sat)
(exit)
```

gives a proof that starts with
```
[before pruning]
t : [0, 2] = [0, 2]
x : [0, 2] = [0, 2]
y : [0, 2] = [0, 2]
[after pruning] by (<= (+ (^ x 2) (^ y 2)) 1.35)
```

However `(<= (+ (^ x 2) (^ y 2)) 1.35)` is not part of the input. The intput contains `(<= 1.3 (+ (+ (^ x 2) (^ y 2)) 0.05))`.
What is funny is that this happens only in the first step. The following steps show the right formula.

Thanks,
Damien

**Comment by soonhokong** [comment]
@dzufferey, this is because of the simplification step in the preprocessing. I can make an option to disable the step. Do you think it will be useful for you?

> What is funny is that this happens only in the first step. The following steps show the right formula.

I'm not sure that this is the case, could you double check? I think the following line made you think that it happens:

```
 29 [after pruning] by (<= 1.3 (+ (+ (^ x 2) (^ y 2)) 0.05))
```

Note that the constraint is `1.3 <= x^2 + y^2 + 0.05` in infix-form, and it's different from "x^2 + y^2 <= 1.35".

**Comment by dzufferey** [comment]
@soonhokong you were right it is a different constraint `(not (< (+ 1.3 0.05) (+ (^ x 2) (^ y 2))))` that gets simplified.

With Sean, we are working on some interpolation, so I need to associate each clause in the proof with the formula from which it comes. Right now I'm doing that just by syntactic matching, so I need the clause to be the same (up to negation) in the input formula and the proof.

Does dReal support named clauses ? `(! formula :named id)`
Maybe that could also be used to in the proof.

Otherwise, a flag to disable simplification would work.

Thanks.

**Comment by soonhokong** [comment]
> Does dReal support named clauses ? (! formula :named id)

I'm not sure that OpenSMT supports that. Possibly, it's not. Feel free to test it!

> Otherwise, a flag to disable simplification would work.

I'll do this.

**Comment by dzufferey** [comment]
It seems OpenSMT does not support named clauses. When I try I get `syntax error, unexpected TK_ANNOT`.

**Comment by soonhokong** [comment]
@dzufferey, I see. I'll add an option to disable simplification soon (#125).

**Comment by soonhokong** [comment]
@dzufferey, please try `--no-simp`.

**Comment by dzufferey** [comment]
That works. Thanks.
