### ISSUE TITLE
--in option

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#130]
For now, running dReal without any parameter waits for standard input. It seems it confuses people so we're thinking about changing its behavior to print out help messages.

I'm thinking about adding a new option "--stdin" which simulate the old behavior.

@dzufferey, does this proposal sound reasonable to you?

**Comment by dzufferey** [comment]
That sounds fine. For instance, z3 has a similar behaviour where you have to give the "-in" option, otherwise it prints an error/help message.

**Comment by soonhokong** [comment]
Great. I'll implement this soon.
