### ISSUE TITLE
Unknown term logic error (possibly from opensmt_mk_num)

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#131]
This code

```julia
ctx = opensmt_mk_context(@compat UInt32(1))
opensmt_set_precision(ctx, 0.00001)
A = opensmt_mk_real_var( ctx, "A" , 0.0, 1.0)
B = opensmt_mk_real_var( ctx, "B" , 0.0, 1.0)

ite = opensmt_mk_ite(ctx, opensmt_mk_gt(ctx, A, opensmt_mk_num(ctx, 0.4)),
                          opensmt_mk_num(ctx, 0.3),
                          opensmt_mk_num(ctx, 0.4))
eq = opensmt_mk_gt(ctx, B, ite)
opensmt_assert( ctx, eq)
res = opensmt_check( ctx );
println("res is ", res == -1 ? "unsat" : "sat")
```

Is causing this error

```
terminate called after throwing an instance of 'std::logic_error'
  what():  translateEnodeExprNode: Unknown Term
```

I think the culprit is the recently added `mk_num`, because if you replace that with a variable the error does not occur.  I added this example as `tests/ifelse.jl in dReal.jl`

**Comment by soonhokong** [comment]
I think the error comes from the use of `opensmt_mk_ite`. When dReal handles a `.smt2` file, it has a preprocessing step which eliminate all ITEs in a file. When we use C APIs, we don't have the preprocessing step and it caused this error.

Let me think about a possible solution for the problem...

> I think the culprit is the recently added mk_num, because if you replace that with a variable the error does not occur.

Could you check that this is the case?

**Comment by soonhokong** [comment]
I added a patch in facdbff and an [example](https://github.com/dreal/dreal3/blob/master/src/tests/c_api/dreal_jl_02.c). Could you check it doesn't break any existing working examples?

**Comment by zenna** [comment]
No existing tests are broken.

**Comment by soonhokong** [comment]
Thanks for checking it. I'll close this one for now. Please re-open this one if you find any issue.
