### ISSUE TITLE
Errors during make dReal

### ISSUE THREAD

**Issue by afragop72** [dreal/dreal3#134]
Hi

I am using gcc 5.0 and towards make I am receiving the following errors.

Thx

Note on using the library:

Please set your CXXFLAGS to " -I/dreal/build/release/external/src/CAPD4/capdExt/filibsrc/. -Wall -Wextra -std=c++11 -D__USE_FILIB__ -w -frounding-math" when compiling programs using the installed filib++.

=== configuring in capdAux (/dreal/build/release/external/src/CAPD4/capdAux)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/dreal/build/release'  'CC=/usr/local/bin/gcc-5' 'CXX=/usr/local/bin/g++-5' 'CXXFLAGS=-Wall -Wextra -std=c++11 -D__USE_FILIB__ -w' 'LDFLAGS=-D__USE_FILIB__' '--without-gui' '--without-boost' '--with-mpfr=no' '--with-filib=yes' '--disable-shared' --cache-file=.././capd.cache --srcdir=.
configure: loading cache .././capd.cache
checking for /dreal/build/release/external/src/CAPD4/capdAux/./../capdMake... yes
Exporting PKG_CONFIG_PATH as /dreal/build/release/external/src/CAPD4/lib/pkgconfig-dev:/dreal/build/release/external/src/CAPD4/lib/pkgconfig-dev
checking for gcc... (cached) /usr/local/bin/gcc-5
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... (cached) o
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/local/bin/gcc-5 accepts -g... (cached) yes
checking for /usr/local/bin/gcc-5 option to accept ISO C89... (cached) none needed
checking whether /usr/local/bin/gcc-5 understands -c and -o together... (cached) yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... (cached) /usr/bin/install -c
checking whether build environment is sane (CAPD implementation)... yes
checking for a thread-safe mkdir -p... ../capdMake/install-sh -c -d
checking for gawk... (cached) awk
checking whether make sets $(MAKE)... (cached) yes
checking for style of include used by make... GNU
checking how to create a pax tar archive... (cached) gnutar
checking dependency style of /usr/local/bin/gcc-5... (cached) gcc3
checking build system type... (cached) x86_64-apple-darwin14.3.0
checking host system type... (cached) x86_64-apple-darwin14.3.0
HOST INFORMATION : x86_64-apple-darwin14.3.0
 X x86_64 X apple X  darwin14.3.0
./configure: line 4568: syntax error near unexpected token `X11,'
./configure: line 4568: `  PKG_CHECK_MODULES(X11, x11,'
configure: error: ./configure failed for capdAux

**Comment by soonhokong** [comment]
Thanks for the report. I will check it when I go to my office. I guess you're using OSX. Could you confirm that you have installed the following packages?

 automake autoconf libtool git cmake pkg-config

**Comment by soonhokong** [comment]
As far as I remember, the error occurs because `pkg-config` is not installed. Actually, it was missing in the documentation. I just added it in 82e9217405d2344df5e1b8fa2bfc47ae71f4a244.

**Comment by afragop72** [comment]
Hi Soonho

Thanks for the quick feedback.

Actually, I hadn’t installed pkg-config and when I installed it make was proceed with no problem.

Regards,

—Tasos Fragopoulos

On Jun 13, 2015, at 8:38 PM, Soonho Kong <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I remember, the error occurs because pkg-config is not installed. Actually, it was missing in the documentation. I just added it in 82e9217<https://github.com/dreal/dreal3/commit/82e9217405d2344df5e1b8fa2bfc47ae71f4a244>.

—
Reply to this email directly or view it on GitHub<https://github.com/dreal/dreal3/issues/134#issuecomment-111735924>.


CONFIDENTIALITY  NOTICE:
This email and any attachments transmitted with it are confidential and intended for the use of individual or entity to which it is addressed. If you have received this email in error, please delete it immediately and inform the sender. Unless you are the intended recipient, you may not use, disclose, copy or distribute this email or any attachments included. The contents of the emails including any attachments may be subjected to copyrights law, In such case the contents may not be copied, adapted, distributed or transmitted without the consent of the copyright owner.
