### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by afragop72** [dreal/dreal3#135]
Hi 

I am in the process of installing dReach.
On the step,
eval `opam config env --root=<ABSOLUTE_HOMEPATH>/ocamlbrew/ocaml-4.00.1/.opam`

I cannot see the directory structure under my homepath and I am receiving an error towards the execution of the above command.

Regards

--Tasos

PS. I am installing it in OSX Yosemite 10.10.3

**Comment by soonhokong** [comment]
@afragop72, thanks for the report. I'll check it this evening. In the meantime, could you try the precompiled binary in https://github.com/dreal/dreal3/releases/download/v3.15.06/dReal-3.15.06-darwin.zip ? It should work without a problem.

**Comment by soonhokong** [comment]
@afragop72, I just updated the `doc/osx-gcc.md` file. Please try:

    eval `opam config env`
    opam update
    opam install ocamlfind batteries oasis

If you still have a problem, please let us know.

**Comment by afragop72** [comment]
Hi,

Now it seems to be OK.

Actually, I have seen a folder dReal created under my door dir, where I went to dreal/tools and I run make and files compiled with no problem.

I will keep you posted for any future issues.

Thanks and Regards,

—Tasos

On Jun 15, 2015, at 8:59 PM, Soonho Kong <notifications@github.com<mailto:notifications@github.com>> wrote:


@afragop72<https://github.com/afragop72>, I just updated the doc/osx-gcc.md file. Please try:

eval `opam config env`
opam update
opam install ocamlfind batteries oasis


If you still have a problem, please let us know.

—
Reply to this email directly or view it on GitHub<https://github.com/dreal/dreal3/issues/135#issuecomment-112153979>.


CONFIDENTIALITY  NOTICE:
This email and any attachments transmitted with it are confidential and intended for the use of individual or entity to which it is addressed. If you have received this email in error, please delete it immediately and inform the sender. Unless you are the intended recipient, you may not use, disclose, copy or distribute this email or any attachments included. The contents of the emails including any attachments may be subjected to copyrights law, In such case the contents may not be copied, adapted, distributed or transmitted without the consent of the copyright owner.

**Comment by soonhokong** [comment]
@afragop72, great!!
