### ISSUE TITLE
Add Forall to C-API 

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#137]

**Comment by soonhokong** [comment]
Please see https://github.com/dreal/dreal3/blob/1a501a43d5a7fe899a2aa830434b23200a012e20/src/tests/c_api/exist_forall_01.c#L45-L46.

The main purpose of this example is to find a minimum of a function 

![screen shot 2015-07-07 at 3 20 20 am](https://cloud.githubusercontent.com/assets/403281/8540831/26507214-2457-11e5-819d-ede616a1cfeb.png)

I think the new ingredient here is `opensmt_mk_forall_real_var` at line 46, which define a universally quantified variable.

**Comment by soonhokong** [comment]
We can have two types of variables -- existentially and universally quantified variables. For now, we assume that we're handling a formula in prenex normal form such as ∃. x1 ... xn ∀ y1 ... yn F where F is a quantifier-free part.
