### ISSUE TITLE
Optimization is unsat

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#140]
DReal says there's no optimal solution, which must be wrong.
```julia
n_167 = 3
f(x) = sum([((100*(x[i]^2 -x[j])^2 + (1 - x[j])^2)^2)/4000 - cos(100*(x[i]^2) - x[j])^2 + (1 - x[j])^2 + 1 for i = 1:n_167, j = 1:n_167])
x = [Var(Float64, -10000.0, 10000.0) for i = 1:n_167]
y = [ForallVar(Float64, -10000.0, 10000.0) for i = 1:n_167]
add!(f(x) <= f(y))
is_satisfiable()
#false
```

**Comment by soonhokong** [comment]
Is it problem 167 from the paper?

**Comment by soonhokong** [comment]
I got it. Never mind.

**Comment by zenna** [comment]
Hold on, it might be a stupid mistake by me (not resetting context)

**Comment by soonhokong** [comment]
I was able to reproduce the problem. I think this is a bug in IBEX.

```
Before pruning using ibex_fwdbwd((cost-((((((((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000)+(-1*cos((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)+1))))+(((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)+1)))))=0)
cost : [ ENTIRE ] = [ ENTIRE ]	[ ENTIRE ]
x1 : [-100000, 100000] = [-100000, 100000]	[-100000, 100000]
x2 : [-100000, 100000] = [-100000, 100000]	[-100000, 100000]
ibex interval = ([-100000, 100000] ; [-100000, 100000] ; [ ENTIRE ]) (before)
function = _f_0:(x2,x1,cost)->(cost-((((((((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000)+(-1*cos((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)+1))))+(((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)+1)))))
domain   = [0, 0]
ibex interval = empty vector (after)
After pruning using ibex_fwdbwd((cost-((((((((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000)+(-1*cos((((100*(x1^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x1^2+(-1*x2))^2)+(1+(-1*x2))^2)+1))))+(((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x1))^2)+(1+(-1*x1))^2)+1))))+(((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)^2/4000))+(-1*cos((((100*(x2^2+(-1*x2))^2)+(1+(-1*x2))^2)+1)))))=0)
cost : [ ENTIRE ] = [ empty ]	[ ENTIRE ]
x1 : [-100000, 100000] = [-100000, 100000]	[-100000, 100000]
x2 : [-100000, 100000] = [-100000, 100000]	[-100000, 100000]
```

Here it evaluates the constraint using the assignment x1 = [-1000000, 1000000] and x2 = [-1000000, 1000000]. Then somehow, it concludes that cost = [empty], which is wrong.

It's interesting that if we provide a smaller interval for x1 and x2 such as [0, 10]. It works. I'll check the latest version of IBEX. If I can still generate the behavior, I'll submit a bug report there.

**Comment by soonhokong** [comment]
> Hold on, it might be a stupid mistake by me (not resetting context)

I can reproduce this one with dOp:

```
prec: 0.01

var:
    x1 : [-10000,10000]
    x2 : [-10000,10000]

ctr:
    (100 * (x1^2 - x1)^2 + (1 - x1)^2)^2 / 4000 - cos(100 * (x1^2 - x1)^2 + (1-x1)^2 + 1) +
    (100 * (x1^2 - x2)^2 + (1 - x2)^2)^2 / 4000 - cos(100 * (x1^2 - x2)^2 + (1-x2)^2 + 1) +
    (100 * (x2^2 - x1)^2 + (1 - x1)^2)^2 / 4000 - cos(100 * (x2^2 - x1)^2 + (1-x1)^2 + 1) +
    (100 * (x2^2 - x2)^2 + (1 - x2)^2)^2 / 4000 - cos(100 * (x2^2 - x2)^2 + (1-x2)^2 + 1)
```

**Comment by zenna** [comment]
Ok

**Comment by soonhokong** [comment]
As I mentioned, if I provide a smaller interval, it finds a solution.

**Comment by soonhokong** [comment]
Here is a small example which shows the problem:

```
(set-logic QF_NRA)
(declare-fun exists x1 () Real [-100000, 100000])
(declare-fun exists x2 () Real [-100000, 100000])
(declare-fun cost () Real)
(assert
  (= cost (cos (+ (^ x1 30) (^ x2 30))))
)
(check-sat)         ;; <- UNSAT
(exit)
```

I think there is a bug in IBEX handling `cos` function. When it gets a huge interval, it return an empty interval. I'll open an issue in IBEX later. I don't think they can fix the problem before our deadline. Let's give a smaller interval to avoid the problem temporarily.

**Comment by soonhokong** [comment]
BTW, the paper includes many mistakes. For instance, this problem 167, they claim that the global minimum is located at (1.0, 1.0) for two-dimensional case. However, this is not the case. f(1.0, 1.0) = -4 * cos(1) which is -2.1612. The global minimum is -4 * cos(0) = -4. Our tool finds somewhere near the global optimum. With precision=0.001, it finds the following for example:

```
	x1 = [-0.169648, -0.169471]
	x2 = [-0.169552, -0.169166]
	min = [-3.97193, -3.97182]
```

**Comment by soonhokong** [comment]
I bet @scungao likes this picture :-)

![screen shot 2015-07-08 at 11 23 59 pm](https://cloud.githubusercontent.com/assets/403281/8587372/7123703a-25c8-11e5-9914-31a2363f6015.png)

**Comment by zenna** [comment]
@soonhokong Yeah I noticed this.  I looked at the original function.  The minimum is at 1,1, but they missed a parents (the cos is closed before the +1)

```julia
  sum([((100*(x[i]^2 -x[j])^2 + (1 - x[j])^2)^2)/4000 - cos(100*(x[i]^2 - x[j])^2 + (1 - x[j])^2) + 1 for i = 1:length(x), j = 1:length(x)])
```

**Comment by zenna** [comment]
What are you using to plot?

**Comment by soonhokong** [comment]
I see.. Actually, I found some other typos here and there in the paper. Then I had no way to make sure whether the paper is correct or dReal is correct. Visualization is one way of doing a sanity-check.. (only for 1D and 2D cases though).

I'm using http://matplotlib.org . Many people told me that it's pretty good. The one that I'm using in particular is based on this example, http://matplotlib.org/examples/mplot3d/trisurf3d_demo.html .

**Comment by zenna** [comment]
An easy way to test whether dReal is correct or the paper is correct is to just evaluate the function (assuming you/they wrote it down right).

**Comment by soonhokong** [comment]
yep :-)

**Comment by soonhokong** [comment]
It seems that we can use https://github.com/stevengj/PyPlot.jl to use matplotlib in Julia..

**Comment by zenna** [comment]
Yep, I really like Gadfly, but it doesnt support 3d plots

**Comment by scungao** [comment]
LOL! Let's get both min and max on this!

**Comment by soonhokong** [comment]
Haha.. I'll get you high-res version soon.

**Comment by soonhokong** [comment]
@zenna, this one is fixed as well.. Please check and let me know if it's not the case.
