### ISSUE TITLE
DReal doesn't like infinity

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#143]
```julia
julia> using DReal

julia> A = Var(Float64) # unbounded
DReal.Ex{Float64}(Ptr{Void} @0x000000000308c540,Set(ASCIIString["x0"]))

julia> add!(A >= -Inf)
Set(ASCIIString["x0"])

julia> is_satisfiable()
false

```

**Comment by soonhokong** [comment]
hmm.. I'll investigate this one.

**Comment by soonhokong** [comment]
Well. it turns out that it's IBEX which doesn't like infinity. In the end, we call the following function to convert a double value `-INFINITY` into an IBEX interval:

  https://github.com/dreal-deps/ibex-lib/blob/master/src/arithmetic/ibex_Interval.h#L949-L951

It converts -INFINITY into `[empty]`. Then the following operations conclude that it's UNSAT.

I think there is reason why they did this conversion. I'll ask IBEX-team the reason and also possible way of representing [-oo, -oo] in IBEX.

**Comment by zenna** [comment]
More issues:

```julia
julia> X = Var(Float64, -Inf, Inf)
Ex{Float64}(Ptr{Void} @0x0000000008556900,Set{ASCIIString}({"x0"}))

julia> add!(sin(X) > 0.0)
Set{ASCIIString}({"x0"})

julia> is_satisfiable()
true

julia> model(X)
[1.7976931348623157e308 Inf]
```

But...

```julia
julia> X = Var(Float64) # unbounded
Ex{Float64}(Ptr{Void} @0x000000000704be00,Set{ASCIIString}({"x0"}))

julia> add!(sin(X) > 0.0)
Set{ASCIIString}({"x0"})

julia> is_satisfiable()
false
```

**Comment by soonhokong** [comment]
@zenna, the problem is more complicated than I expected. See the discussion at https://github.com/ibex-team/ibex-lib/issues/148.

Anyway, I think we find a workaround for the problem. I'll test it and let you know how it works.

**Comment by soonhokong** [comment]
@zenna, could you try https://dl.dropboxusercontent.com/u/10377018/dReal-3.15.07.02-linux-shared-libs.tar.gz ?

**Comment by zenna** [comment]
Soonho.

This fixes the first one but the second remains false

```julia
julia> X = Var(Float64) # unbounded
Ex{Float64}(Ptr{Void} @0x000000000704be00,Set{ASCIIString}({"x0"}))

julia> add!(sin(X) > 0.0)
Set{ASCIIString}({"x0"})

julia> is_satisfiable()
false
```

**Comment by soonhokong** [comment]
@zenna, thanks for checking it. I'll work on it.

**Comment by soonhokong** [comment]
I think the second issue has the same origin of #140. I've contacted IBEX-team about it. I'll give you an update when I get a response from them.

**Comment by soonhokong** [comment]
@zenna, when I checked it now. It's fixed. Could you check this one with 3.15.08 version?
