### ISSUE TITLE
does not build with g++-4.8 (but succeed with g++-4.9)

### ISSUE THREAD

**Issue by dzufferey** [dreal/dreal3#146]
With g++-4.8 I get some error in `src/util/cxx11_check.cpp`. Some of the `static_assert` fails.
On the other hand, it builds fine with g++-4.9. Maybe g++-4.8 should be removed from the build scripts?

**Comment by soonhokong** [comment]
I noticed the problem as well. i will relax some conditions later to be compatible with gcc-4.8. For now, you can comment those lines that generated errors.

**Comment by dzufferey** [comment]
Thanks for the info.

**Comment by soonhokong** [comment]
closed by 5cb8f3a0f5587b0db67b9f365a9327033415112d
