### ISSUE TITLE
SMT file and API give different result

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#149]
```lisp
(assert(= x_0 0))
(assert(= x_18 (sin x_1)))
(assert(= x_21 (cos x_2)))
(assert(= x_22 (+ x_21 x_18)))
```

if we write such problem as a smt file, dReal says sat, if we solve it by calling API, dreal says unsat.

**Comment by soonhokong** [comment]
It's because of the known problem in IBEX...

**Comment by scungao** [comment]
Is it easy to isolate the problem? Can we fix the code by ourselves?

**Comment by soonhokong** [comment]
Yes. There is example_04.c test file under src/tests/IBEX directory. It
only includes IBEX code.

I've tried different versions of IBEX last night but they all gave wrong
answers. I will see the internal today.

On Tuesday, August 4, 2015, Sicun Gao <notifications@github.com> wrote:

> Is it easy to isolate the problem? Can we fix the code by ourselves?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/149#issuecomment-127496270>.
>


-- 

Best,
Soonho

**Comment by soonhokong** [comment]
I patched IBEX. See https://github.com/dreal-deps/ibex-lib/commit/40d048f7e443a89c18e970eb90da450291b710f2
