### ISSUE TITLE
unsat with no message

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#18]
old version returns sat. new version returns unsat, without any trace when --verbose. 

(set-logic QF_NRA)
(declare-fun vhat0 () Real)
(declare-fun thehat0 () Real)
(declare-fun zp_0_0 () Real)
(declare-fun vhat1 () Real)
(declare-fun thehat1 () Real)
(declare-fun zp_1_1 () Real)
(declare-fun vhat2 () Real)
(declare-fun thehat2 () Real)
(declare-fun zp_2_2 () Real)
(assert (<= vhat0 5))
(assert (>= vhat0 -5))
(assert (<= thehat0 5))
(assert (>= thehat0 -5))
(assert (<= zp_0_0 5))
(assert (>= zp_0_0 -5))
(assert (<= vhat1 5))
(assert (>= vhat1 -5))
(assert (<= thehat1 5))
(assert (>= thehat1 -5))
(assert (<= zp_1_1 5))
(assert (>= zp_1_1 -5))
(assert (<= vhat2 5))
(assert (>= vhat2 -5))
(assert (<= thehat2 5))
(assert (>= thehat2 -5))
(assert (<= zp_2_2 5))
(assert (>= zp_2_2 -5))
(assert (= (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (+ 0 (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat0) (* 1 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2))))))))) 0.000010)) (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) 1.000000) 0.000000) 0)) vhat1) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) 1.000000) 0.000000) 0)) vhat2) 0)) vhat0) 0)) 0.000010)) (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) 0.000000) 0.000000) 0)) vhat1) (* 1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1))))))) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat0) 0)) 0.000010)) (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) -1.000000) 0.000000) 0)) vhat1) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat0) 0)) 0.000010)) (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) 0.000000) 0.000000) 0)) vhat2) (* 1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2))))))) vhat0) 0)) 0.000010)) (/ (* (- zp_0_0 (* vhat0 (+ (+ 0 (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat0 thehat1)))) (* 0.000000 (sin (- thehat0 thehat1)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat0 thehat2)))) (* 0.000000 (sin (- thehat0 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat0 thehat2))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat0 thehat2)) -1.000000) 0.000000) 0)) vhat2) 0)) vhat0) 0)) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) 0.000000) 0.000000) 0)) vhat0) (* 1 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0))))))) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat1) 0)) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) -1.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat1) 0)) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) 0.000000) 0.000000) 0)) vhat2) 0)) vhat1) (* 1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2))))))))) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) 1.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) 1.000000) 0.000000) 0)) vhat2) 0)) vhat1) 0)) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) 0.000000) 0.000000) 0)) vhat2) (* 1 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2))))))) vhat1) 0)) 0.000010)) (/ (* (- zp_1_1 (* vhat1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat1 thehat0)))) (* 0.000000 (sin (- thehat1 thehat0)))))) (* vhat2 (- (- 0 (* 0.000000 (cos (- thehat1 thehat2)))) (* 0.000000 (sin (- thehat1 thehat2)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat1 thehat2))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat1 thehat2)) -1.000000) 0.000000) 0)) vhat2) 0)) vhat1) 0)) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) 0.000000) 0.000000) 0)) vhat0) (* 1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0))))))) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) vhat2) 0)) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) -1.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) vhat2) 0)) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) 0.000000) 0.000000) 0)) vhat1) (* 1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1))))))) vhat2) 0)) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) -1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) -1.000000) 0.000000) 0)) vhat1) 0)) vhat2) 0)) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) 0.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) 0.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) 0.000000) 0.000000) 0)) vhat1) 0)) vhat2) (* 1 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1))))))))) 0.000010)) (/ (* (- zp_2_2 (* vhat2 (+ (+ 0 (* vhat0 (- (- 0 (* 0.000000 (cos (- thehat2 thehat0)))) (* 0.000000 (sin (- thehat2 thehat0)))))) (* vhat1 (- (- 0 (* 0.000000 (cos (- thehat2 thehat1)))) (* 0.000000 (sin (- thehat2 thehat1)))))))) (+ (* (+ (+ 0 (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat0))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat0)) 1.000000) 0.000000) 0)) vhat0) 0)) (+ (* (- (- 0 (+ (* (* (- 0 (sin (- thehat2 thehat1))) 1.000000) 0.000000) 0)) (+ (* (* (cos (- thehat2 thehat1)) 1.000000) 0.000000) 0)) vhat1) 0)) vhat2) 0)) 0.000010)) 0))
(check-sat)
(exit)

**Comment by scungao** [comment]
oh perhaps because almost everything is evaluated to zero.

**Comment by soonhokong** [comment]
Well.. I got SAT. Could you double check?

```
Solution:
thehat0 : [-5, 5] = [4.9993896484375, 5]
thehat1 : [-5, 5] = [4.9993896484375, 5]
thehat2 : [-5, 5] = [4.9993896484375, 5]
vhat0 : [-5, 5] = [4.9993896484375, 5]
vhat1 : [-5, 5] = [4.9993896484375, 5]
vhat2 : [-5, 5] = [4.9993896484375, 5]
zp_0_0 : [-5, 5] = [4.9993896484375, 5]
zp_1_1 : [-5, 5] = [4.9993896484375, 5]
zp_2_2 : [-5, 5] = [4.9993896484375, 5]
sat
```

**Comment by scungao** [comment]
I guess I used an earlier version.

**Comment by soonhokong** [comment]
Good to know that something is improved ;-0
