### ISSUE TITLE
dReach cannot run dReal; usage message for dReal is displayed and exits immediately

### ISSUE THREAD

**Issue by mtrberzi** [dreal/dreal3#222]
I'm trying to do some work with dReach, but the frontend seems to have trouble invoking dReal correctly. I've been able to reproduce this on dReal v3.16.1.01 commit 156be53c7e18 with a file I generated by hand as well as one of the benchmark input files.

`dReach -k 1 -l 1 dreal3/2d_oscillator.drh`
produces the following output:
```
dReal Options: --visualize --precision=0.001
SMT: parallel-capacitor_1_0.smt2, PATH : [1,1]
dReal v3.16.1.01 (commit 156be53c7e18) : delta-complete SMT solver

USAGE: dReal [OPTIONS] <input file>
(snipped)
For k = 1, dReach tried 1 feasible paths, all of them are unsat.
```

Let me know if you need more information.

**Comment by soonhokong** [comment]
Hi @mtrberzi,

Could you send me the `drh` file and the output of `pwd` in your working directory?

**Comment by mtrberzi** [comment]
After applying the corrections suggested in #224 I still encounter this problem when invoking dReach as shown above.

**Comment by soonhokong** [comment]
@mtrberzi, could you send me the .drh file?

**Comment by mtrberzi** [comment]
Sorry, my mistake; I was using an old script which had the wrong command line parameter.

**Comment by soonhokong** [comment]
@mtrberzi, it's OK. When you have other questions, please feel free to either open an issue or send me an email.
