### ISSUE TITLE
cannot be handled by any TSolver

### ISSUE THREAD

**Issue by Heizmann** [dreal/dreal3#232]
While running dReal-3.16.04-linux on the [attached SMT script](https://github.com/dreal/dreal3/files/211202/eindhoven.smt2.txt) I obtain the following error message.

    # WARNING: Running in INCOMPLETE mode
    # Error: (<= (* -1 motzkin_2_0) -0)  cannot be handled by any TSolver. Did you disable some solver in the configure file ? (triggered at /usr0/home/soonhok/work/dreal3/src/opensmt/egraph/EgraphSolver.C, 88)

**Comment by soonhokong** [comment]
@Heizmann, please try to use `(set-logic QF_NRA)` instead of `(set-logic QF_LRA)`. It gives me the following result:

```
Solution:
liipp_0__y : [ ENTIRE ] = [3.595386269724631e+307, 3.595386269724632e+307]
liipp_0_c : [ ENTIRE ] = [ -INFTY ]
liipp_1__y : [ ENTIRE ] = [0, 0]
liipp_1_c : [ ENTIRE ] = [-0, 0.0009765624999999999]
motzkin_0_0 : [ ENTIRE ] = [3.595386269724631e+307, 3.595386269724632e+307]
motzkin_1_0 : [ ENTIRE ] = [0, 0]
motzkin_2_0 : [ ENTIRE ] = [3.595386269724631e+307, 3.595386269724632e+307]
delta-sat with delta = 0.00100000000000000
```

Also, please have `(exit)` at the end of script.

**Comment by Heizmann** [comment]
Thanks for the hints. I used the wrong logic accidentally.
