### ISSUE TITLE
Best parameters for some script

### ISSUE THREAD

**Issue by Heizmann** [dreal/dreal3#233]
A satisfying assignment for the [attached SMT script](https://github.com/dreal/dreal3/files/211251/disjuctiveInvariant01.smt2.txt) allows me to find an invariant for a simple loop.
The release dReal-3.16.04-linux does not provide a solution within a few minutes. I do not use any parameters. Are there some parameters for which a solution is found?

I am not sure if the issue tracker is the right place for this question. Feel free to remove it here if you like to.

**Comment by soonhokong** [comment]
@Heizmann, it seems that the problem is mostly linear and includes a few high-order polynomial constraints. In this case, it's better to use [Z3](https://github.com/Z3Prover/z3/). Please have `(get-model)` between `(check-sat)` and `(exit)`. You will get the model in the end of solving.
