### ISSUE TITLE
Forall problems in DNF form trigger assertion.

### ISSUE THREAD

**Issue by cgd8d** [dreal/dreal3#243]
Current behavior is to trigger an assertion in translate_enode_to_exprctr which is rather cryptic; preferred behavior is to provide a more descriptive error, or handle DNF format.

Example input to trigger issue:

```
(set-logic QF_NRA)
(declare-fun x1 () Real)
(declare-fun forall x2 () Real[7.0, 50.0])
(assert (<= -3.0 x1))
(assert (<= x1 3.14))
(assert
 (forall
  ((x2 Real))
  (or
   (and
    (>= x1 x2)
    (>= x1 0))
   (>= x1 x2))))
(check-sat)
(exit)
```

**Comment by soonhokong** [comment]
Thanks, I'll check.

**Comment by soonho-tri** [comment]
@cgd8d, FYI, we have a new version, [dReal4](https://github.com/dreal/dreal4), which can handle this (note: no need to have `(declare-fun forall x2 () Real[7.0, 50.0])`).
