### ISSUE TITLE
Atoms containing only forall variables trigger assertion.

### ISSUE THREAD

**Issue by cgd8d** [dreal/dreal3#244]
In contractor_generic_forall::handle_disjunction, "boxes" gets one entry for every variable of type "exists".  When there are no "exists" variables, boxes is an empty vector, and hull(boxes) raises an assertion.

Example input to trigger issue:

```
(set-logic QF_NRA)
(declare-fun x1 () Real)
(declare-fun forall x2 () Real[7.0, 50.0])
(assert (<= -3.0 x1))
(assert (<= x1 3.14))
(assert
 (forall
  ((x2 Real))
  (and
   (>= x2 20)
   (<= x1 x2))))
(check-sat)
(exit)
```

**Comment by soonhokong** [comment]
Thanks, I'll check.

**Comment by cgd8d** [comment]
Just checking: is the fix for this as simple as

```
--- a/src/contractor/contractor_generic_forall.cpp
+++ b/src/contractor/contractor_generic_forall.cpp
@@ -513,7 +513,7 @@ void contractor_generic_forall::handle_disjunction(contractor_status & cs, vecto
             }
         }
     }
-    cs.m_box = hull(boxes);
+    if(boxes.size() > 0) cs.m_box = hull(boxes);
     return;
 }
```

at https://github.com/dreal/dreal3/blob/v3.16.06.03/src/contractor/contractor_generic_forall.cpp#L516?

**Comment by soonhokong** [comment]
I'm sorry for all the delays in this area (exist-forall). I've been busy working on other topics and refactoring the infrastructures (i.e. `contractor_status`). I'll check whether this patch is ok or not later today.

**Comment by soonhokong** [comment]
@cgd8d, it's fixed by https://github.com/dreal/dreal3/commit/e6136c8813ee423fad5dc82f705d04a59e2f07a4.

**Comment by cgd8d** [comment]
Awesome -- thanks!
