### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by githwxi** [dreal/dreal3#266]
I was testing the parser of dReal.

I observed a silent core dump when trying dReal on the following input (which was automatically generated). It seems that some run-time checks are needed...

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;By [patsolve_smt2]:
;;
(declare-sort s2rt_cls 0)
(declare-sort s2rt_eff 0)
(declare-sort s2rt_type 0)
(declare-sort s2rt_vtype 0)
(declare-sort s2rt_t0ype 0)
(declare-sort s2rt_vt0ype 0)
(declare-sort s2rt_prop 0)
(declare-sort s2rt_view 0)
(declare-sort s2rt_tkind 0)
(declare-sort s2rt_error 0)
;;
(declare-fun sqrt_real!801 (Real) Real)
(push 1)
(declare-fun x$981$982!4319 () Real)
(declare-fun x$987$988!4325 () Real)
(push 1)
(push 1)
(declare-fun x$851!4180 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$852!4181 () Real)
(declare-fun y$853!4182 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$854!4183 () Real)
(declare-fun y$855!4184 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$856!4185 () Real)
(declare-fun y$857!4186 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$858!4187 () Real)
(declare-fun y$859!4188 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun i$860!4189 () s2rt_int)
(declare-fun x$861!4190 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$862!4191 () Real)
(declare-fun i$863!4192 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun i$864!4193 () s2rt_int)
(declare-fun x$865!4194 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$866!4195 () Real)
(declare-fun i$867!4196 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun i$868!4197 () s2rt_int)
(declare-fun x$869!4198 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$870!4199 () Real)
(declare-fun i$871!4200 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$872!4201 () Real)
(declare-fun y$873!4202 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$874!4203 () Real)
(declare-fun y$875!4204 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$876!4205 () Real)
(declare-fun y$877!4206 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$878!4207 () Real)
(declare-fun y$879!4208 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$880!4209 () Real)
(declare-fun y$881!4210 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$882!4211 () Real)
(declare-fun y$883!4212 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$884!4213 () Real)
(declare-fun i$885!4214 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$886!4215 () Real)
(declare-fun i$887!4216 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$888!4217 () Real)
(declare-fun i$889!4218 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$890!4219 () Real)
(declare-fun i$891!4220 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$892!4221 () Real)
(declare-fun i$893!4222 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$894!4223 () Real)
(declare-fun i$895!4224 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun i$896!4225 () s2rt_int)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$897!4226 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$898!4227 () Real)
(assert (gte_real_real x$898!4227 (int2real 0)))
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$899!4228 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$900!4229 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun x$901!4230 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun r$934!4271 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun r$935!4272 () Real)
(push 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun r$936!4273 () Real)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun A$902!4239 () Real)
(declare-fun B$903!4240 () Real)
(declare-fun C$904!4241 () Real)
(assert (gt_real_real A$902!4239 (int2real 0)))
(push 1)
(assert (forall ((x!4003 Real)) (=> (gte_real_real x!4003 (int2real 0)) (s2exp_fun (and (eq_real_real x!4003 (mul_real_real (sqrt_real!801 x!4003) (sqrt_real!801 x!4003))) unit_p)))))
(assert (gte_real_real (sub_real_real (mul_real_real B$903!4240 B$903!4240) (mul_real_real (mul_real_real (int2real 4) A$902!4239) C$904!4241)) (int2real 0)))
(push 1)
(push 1)
(assert (not (gte_real_real (sub_real_real (mul_real_real B$903!4240 B$903!4240) (mul_real_real (mul_real_real (int2real 4) A$902!4239) C$904!4241)) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 764(line=56, offs=11) -- 764(line=56, offs=11)")
(check-sat)
(pop 1)
(pop 1)
(push 1)
(push 1)
(push 1)
(assert (not (eq_real_real (add_real_real (add_real_real (mul_real_real (mul_real_real A$902!4239 (div_real_real (add_real_real (neg_real B$903!4240) (sqrt_real!801 (sub_real_real (mul_real_real B$903!4240 B$903!4240) (mul_real_real (mul_real_real (int2real 4) A$902!4239) C$904!4241)))) (mul_real_real (int2real 2) A$902!4239))) (div_real_real (add_real_real (neg_real B$903!4240) (sqrt_real!801 (sub_real_real (mul_real_real B$903!4240 B$903!4240) (mul_real_real (mul_real_real (int2real 4) A$902!4239) C$904!4241)))) (mul_real_real (int2real 2) A$902!4239))) (mul_real_real B$903!4240 (div_real_real (add_real_real (neg_real B$903!4240) (sqrt_real!801 (sub_real_real (mul_real_real B$903!4240 B$903!4240) (mul_real_real (mul_real_real (int2real 4) A$902!4239) C$904!4241)))) (mul_real_real (int2real 2) A$902!4239)))) C$904!4241) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 756(line=56, offs=3) -- 778(line=56, offs=25)")
(check-sat)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(declare-fun A$906!4243 () Real)
(declare-fun B$907!4244 () Real)
(declare-fun C$908!4245 () Real)
(assert (gt_real_real A$906!4243 (int2real 0)))
(push 1)
(assert (forall ((x!4003 Real)) (=> (gte_real_real x!4003 (int2real 0)) (s2exp_fun (and (eq_real_real x!4003 (mul_real_real (sqrt_real!801 x!4003) (sqrt_real!801 x!4003))) unit_p)))))
(assert (gte_real_real (sub_real_real (mul_real_real B$907!4244 B$907!4244) (mul_real_real (mul_real_real (int2real 4) A$906!4243) C$908!4245)) (int2real 0)))
(push 1)
(push 1)
(assert (not (gte_real_real (sub_real_real (mul_real_real B$907!4244 B$907!4244) (mul_real_real (mul_real_real (int2real 4) A$906!4243) C$908!4245)) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 1010(line=73, offs=11) -- 1010(line=73, offs=11)")
(check-sat)
(pop 1)
(pop 1)
(push 1)
(push 1)
(push 1)
(assert (not (eq_real_real (add_real_real (add_real_real (mul_real_real (mul_real_real A$906!4243 (div_real_real (sub_real_real (neg_real B$907!4244) (sqrt_real!801 (sub_real_real (mul_real_real B$907!4244 B$907!4244) (mul_real_real (mul_real_real (int2real 4) A$906!4243) C$908!4245)))) (mul_real_real (int2real 2) A$906!4243))) (div_real_real (sub_real_real (neg_real B$907!4244) (sqrt_real!801 (sub_real_real (mul_real_real B$907!4244 B$907!4244) (mul_real_real (mul_real_real (int2real 4) A$906!4243) C$908!4245)))) (mul_real_real (int2real 2) A$906!4243))) (mul_real_real B$907!4244 (div_real_real (sub_real_real (neg_real B$907!4244) (sqrt_real!801 (sub_real_real (mul_real_real B$907!4244 B$907!4244) (mul_real_real (mul_real_real (int2real 4) A$906!4243) C$908!4245)))) (mul_real_real (int2real 2) A$906!4243)))) C$908!4245) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 1002(line=73, offs=3) -- 1024(line=73, offs=25)")
(check-sat)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(pop 1)
(push 1)
(push 1)
(assert (not (gt_real_real (int2real 1) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 1112(line=79, offs=19) -- 1112(line=79, offs=19)")
(check-sat)
(pop 1)
(pop 1)
(assert (eq_real_real (add_real_real (add_real_real (mul_real_real (mul_real_real (int2real 1) x$981$982!4319) x$981$982!4319) (mul_real_real (int2real 1) x$981$982!4319)) (int2real (neg_int 1))) (int2real 0)))
(push 1)
(push 1)
(assert (not (gt_real_real (int2real 1) (int2real 0))))
(echo "/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve/ATS-extsolve-smt2/TEST/quadratic.dats: 1168(line=81, offs=19) -- 1168(line=81, offs=19)")
(check-sat)
(pop 1)
(pop 1)
(assert (eq_real_real (add_real_real (add_real_real (mul_real_real (mul_real_real (int2real 1) x$987$988!4325) x$987$988!4325) (mul_real_real (int2real 1) x$987$988!4325)) (int2real (neg_int 1))) (int2real 0)))
(push 1)
(pop 1)
(push 1)
(pop 1)
(push 1)
(push 1)
(pop 1)
(pop 1)
(pop 1)

**Comment by soonhokong** [comment]
@githwxi, thanks for the report. Here, the main issue is that it doesn't have `(set-logic QF_NRA)` in the beginning.

**Comment by soonhokong** [comment]
- We don't support `gt_real_real`, please use `>` instead (same things apply for `gte_real_real`, etc).
 -  `int2real` is not supported and actually not necessary in dReal.

**Comment by githwxi** [comment]
Thanks. I will get rid of the define-funs soon. So far I am testing the smt2-parser of dReal.

**Comment by soonhokong** [comment]
> So far I am testing the smt2-parser of dReal.

Thanks for doing that. Please let us know if you find any problems.

**Comment by githwxi** [comment]
int2real is mapped to 'to_real'

In SMT-LIBv2, there is a specified function of the name 'to_real' for the Reals_Ints theory.

Maybe you could handle it in dReal in a special way?

**Comment by soonhokong** [comment]
@githwxi, I'll find a way.

**Comment by githwxi** [comment]
By the way, in cvc4, if set-logic is not called, then some kind of default
logic is used *and* a warning message is issued. Seems to be a reasonable
design.

**Comment by soonhokong** [comment]
> By the way, in cvc4, if set-logic is not called, then some kind of default
logic is used and a warning message is issued. Seems to be a reasonable
design.

I totally agree. I'll implement a similar one.
