### ISSUE TITLE
Speed-up in forall

### ISSUE THREAD

**Issue by cgd8d** [dreal/dreal3#278]
In the function “find_CE_via_underapprox”, it seems like the loop over enodes can be short-circuited when the counterexample box is already empty, which can save a significant amount of time.  Would something like the following patch be an appropriate way to do this?

    --- a/src/contractor/contractor_generic_forall.cpp
    +++ b/src/contractor/contractor_generic_forall.cpp
    @@ -369,6 +369,10 @@ box find_CE_via_underapprox(box const & b, unordered_set<Enode*> const & forall_
         unordered_set<Enode*> const var_set(vars.begin(), vars.end());
         ibex::IntervalVector & iv = counterexample.get_values();
         for (Enode * e : vec) {
    +        if (counterexample.is_empty()) {
    +            break;
    +        }
    +
             lbool polarity = p ? l_False : l_True;
             if (e->isNot()) {
                 e = e->get1st();

**Comment by soonhokong** [comment]
@cgd8d, this is correct. I'll add the following patch:
```
@@ -394,6 +394,10 @@ box find_CE_via_underapprox(box const & b, unordered_set<Enode*> const & forall_
             ss << "find_CE_via_underapprox: unknown constraint type, " << *numctr;
             throw runtime_error(ss.str());
         }
+        if (iv.is_empty()) {
+            // stop when counterexample is already empty;
+            return counterexample;
+        }

```
