### ISSUE TITLE
more  syntax errors

### ISSUE THREAD

**Issue by nnarodytska** [dreal/dreal3#31]
./dReal ../../benchmarks/simple/bing_20130301.smt2 
At line 11: syntax error, unexpected TK_NUM, expecting TK_SYM

./dReal ../../benchmarks/simple/bing_20130227.smt2
At line 5: syntax error, unexpected TK_NUM, expecting TK_SYM

**Comment by scungao** [comment]
Hi,

Thanks for letting us know -- the benchmark directory contains many outdated files that use syntax in older versions. We'll clean them up soon.
