### ISSUE TITLE
Forall_t construct [dReal v3.16.04.01] [OSX 10.11.4]

### ISSUE THREAD

**Issue by Nikh13** [dreal/dreal3#310]
Hi,

I was looking into the semantics behind the `forall_t` construct introduced by `dReach` in the paper "Satisfiability Modulo ODEs - Gao, Kong, Clarke". The semantics defined for the `exists forall t` theory does not include a concept of 'mode'. From my understanding it just checks satisfiability of a given formula for the time bounds specified by 't'. But in the dReal paper it has been stated that `forall_t` expects an argument of mode. 

I just wanted to know:
1. Is `forall_t` restricted to the domain of Hybrid Automata as mentioned in dReach where you have the concept of mode? 
2. If not, then how would I go about taking advantage of the semantics of `forall_t` without the use of mode?

Thanks,
Nikhil Loney

**Comment by soonho-tri** [comment]
Switched to email discussion.

**Comment by shrey183** [comment]
Hi,
I have the same question. Could you please give a clarification regarding this issue?
