### ISSUE TITLE
BUILD_SHARED_LIB=ON → disaster

### ISSUE THREAD

**Issue by mwoehlke-kitware** [dreal/dreal3#316]
I'm trying to build dReal with `BUILD_SHARED_LIB=ON`. It fails _horribly_. Rather than try to include the myriad link errors, here are some brief examples:

```
linking lib/libdop.so (cc)
CMakeFiles/dop.dir/tools/dop/print_latex.cpp.o: In function `operator<<':
.../dreal/src/opensmt/egraph/Enode.h:380: undefined reference to `Enode::print(std::ostream&) const'
CMakeFiles/dop.dir/tools/dop/process.cpp.o: In function `operator()<__gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, Enode*>*, std::vector<std::pair<std::basic_string<char>, Enode*> > >, __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, Enode*>*, std::vector<std::pair<std::basic_string<char>, Enode*> > > >':
.../dreal/src/tools/dop/process.cpp:175: undefined reference to `dreal::starts_with(std::string const&, std::string const&)'
```

```
.../lib/libdreal.so: undefined reference to `filib::fp_traits_base<double>::nan_val'
.../lib/libdreal.so: undefined reference to `ibex::IntervalVector::mid() const'
.../lib/libdreal.so: undefined reference to `glp_ipt_status'
```

This is happening on multiple machines (so far, on Fedora 21 and Ubuntu 14.04, but I suspect the problem is universal), as of @e6d1d49.

CMake arguments:
```
USE_NLOPT=OFF
BUILD_TESTING=OFF
BUILD_SHARED_LIB=ON
CMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined
```

Possibly related to #51. In particular, https://github.com/dreal/dreal3/issues/51#issuecomment-89334447 suggests that this is a known issue that for some reason was not fixed, despite that #51 was closed.

**Comment by mwoehlke-kitware** [comment]
This seems to partially fix the problem, but I'm not sure if it is TRTTD... dReal's build system seems... odd...

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 7c2bb55..13a56a0 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -808,6 +808,11 @@ else()
   add_library(dop ${DOP_SRCS})
 endif()
 
+set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${DREAL_EXTRA_LINKER_FLAGS} ${EXTERNAL_LD_FLAGS}")
+
+target_link_libraries(dreal ${EXTRA_LIBS})
+target_link_libraries(dop dreal ${EXTRA_LIBS})
+
 add_dependencies(dop PICOSAT)
 add_dependencies(dop IBEX)
 add_dependencies(dop ADEPT)
```

**Comment by mwoehlke-kitware** [comment]
Amendment: the above is only sufficient to *build* dReal... trying to use it:

```
/usr/bin/ld: .../lib/dreal/libglpk.a(libglpk_la-glpapi01.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
.../lib/dreal/libglpk.a: error adding symbols: Bad value
```

It looks like dReal also needs to pass `-DBUILD_SHARED_LIBS` (or at least `-DCMAKE_POSITION_INDEPENDENT_CODE`) to its externals. (Also, what's with `BUILD_SHARED_LIB`? Why not use the standard `BUILD_SHARED_LIBS`?)

**Comment by soonho-tri** [comment]
Hi @mwoehlke-kitware, thanks for the report. This is a known issue and something I've wanted to fix for a long time. I'll take a look at this soon and get back to you. Thanks again.

**Comment by mwoehlke-kitware** [comment]
I think I have things working between the above patch and #317... but the above patch feels like a hack; I suspect there are missing subtleties...

**Comment by soonho-tri** [comment]
@mwoehlke-kitware, thanks for the help!

**Comment by mwoehlke-kitware** [comment]
I'm still getting undefined references...

**Comment by soonho-tri** [comment]
On Ubuntu?

**Comment by mwoehlke-kitware** [comment]
On Linux. I don't have an Ubuntu machine.

**Comment by soonho-tri** [comment]
I see. I just triggered a fresh build on a Linux machine (Ubuntu).

**Comment by soonho-tri** [comment]
FYI, it works on Mac (static/shared) and Ubuntu (static). I forgot to check the shared + Ubuntu combo..

**Comment by mwoehlke-kitware** [comment]
It seems to be "working" because `dreal.pc` has a bunch of spam about other libraries. However, you are doing it wrong; libdreal *itself* uses ibex, capd, etc....; it should link to them. Consumers should *not*¹ link to them directly. This is what causes bugs (and yes, it's a *bug*) like in https://github.com/dreal/dreal3/issues/51#issuecomment-89334447. This would also be more obviously broken if you were using CMake exported targets, as replicating the existing behavior would require adding all of these as *interface* link libraries, which is obviously wrong (they should be private or *maybe* public).

(¹ Probably. I don't know dReal's API well enough to know if they're part of its public API, but I suspect not all of them are.)

Please add `-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined` to your build and you will see the problem. The fix is roughly the patch provided above. (I may submit a PR in a little bit, but I'm only guessing at how to deal with dReal's esoteric build "correctly".)

**Comment by soonho-tri** [comment]
> However, you are doing it wrong; libdreal itself uses ibex, capd, etc....; it should link to them. Consumers should not¹ link to them directly.

Do you mean, `libdreal` should be self-contained by including its dependencies (i.e. ibex, capd)?

**Comment by soonho-tri** [comment]
I was able to reproduce the undefined references by adding `-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined` (on a Ubuntu-14 machine). Having the following patch (that you provided above) seems to solve the problem:

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 7c2bb55..13a56a0 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -808,6 +808,11 @@ else()
   add_library(dop ${DOP_SRCS})
 endif()

+set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${DREAL_EXTRA_LINKER_FLAGS} ${EXTERNAL_LD_FLAGS}")
+
+target_link_libraries(dreal ${EXTRA_LIBS})
+target_link_libraries(dop dreal ${PYTHON_LIBRARIES} ${EXTRA_LIBS})
+
 add_dependencies(dop PICOSAT)
 add_dependencies(dop IBEX)
 add_dependencies(dop ADEPT)
```

**Comment by soonho-tri** [comment]
> It seems to be "working" because dreal.pc has a bunch of spam about other libraries.

1. Speaking of dReal APIs, users should not know about the external APIs that we're using.
2. Does that mean I need to remove all the external libraries from `dreal.pc` by cleaning up the following lines https://github.com/dreal/dreal3/blob/e1aafe68ed4f76ca00394850f2f81b9e0bead90c/src/CMakeLists.txt#L951-L973 ?

**Comment by soonho-tri** [comment]
Sorry for the questions and thanks for the help!

**Comment by mwoehlke-kitware** [comment]
> Do you mean, `libdreal` should be self-contained by including its dependencies (i.e. ibex, capd)?

Exactly. That goes for *any* library, too, not just dreal :smile:.

> Does that mean I need to remove all the external libraries from `dreal.pc` [...]

Well... it's complicated. If dreal is built static, then you *need* those (no such thing as private linking for static libraries). If it's shared, you may be *able* to remove them, in which case *maybe* you should, but opinions might vary on that matter. However, given that you also said:

> users should not know about the external APIs that we're using

...this makes me guess that probably you don't want to leak the list of link libraries when not necessary.

If the patch above isn't striking you as some crazy backward approach, I'll submit a PR shortly. Please don't use the version above; it is quick-and-dirty and works with my current configuration, but at least one bit should be configuration-dependent.

**Comment by soonho-tri** [comment]
@mwoehlke-kitware, thanks for all the answers! TIL a lot!

> If the patch above isn't striking you as some crazy backward approach, I'll submit a PR shortly. Please don't use the version above; it is quick-and-dirty and works with my current configuration, but at least one bit should be configuration-dependent.

Please submit the PR whenever it's ready. Thanks!!

**Comment by mwoehlke-kitware** [comment]
BTW, can you re-open this so the PR can close it properly? TIA!
