### ISSUE TITLE
Turning off ODE doesn't work

### ISSUE THREAD

**Issue by mwoehlke-kitware** [dreal/dreal3#320]
After struggling unsuccessfully to get CAPD to build on macOS, I noticed that it can be disabled with `-DSUPPORT_ODE=OFF`. Unfortunately, when I do this, I get build errors:

```
In file included from .../dreal3/src/opensmt/api/OpenSMTContext.C:33:
In file included from .../dreal3/src/dsolvers/nra_solver.h:33:
In file included from .../dreal3/src/contractor/contractor.h:22:
In file included from .../dreal3/src/contractor/contractor_basic.h:34:
In file included from .../dreal3/src/contractor/contractor_cell.h:32:
.../dreal3/src/contractor/contractor_common.h:77:47: error: unknown type name 'ode_direction'
std::ostream & operator<<(std::ostream & out, ode_direction const & d);
                                              ^
```

I get a similar error on Linux (with GCC). It appears that dReal is trying to build ODE code even if ODE support is disabled. I guess this should either be fixed, or the option should be removed.

**Comment by soonho-tri** [comment]
Thanks for the report. I'll fix it ASAP.

**Comment by soonho-tri** [comment]
> After struggling unsuccessfully to get CAPD to build on macOS

BTW, what's the problem?

**Comment by mwoehlke-kitware** [comment]
> BTW, what's the problem?

Autohell. Screwy errors about macros not existing that should (`AC_MSG_WARN`, `AS_ECHO`; these appear in other places with no problem!) when trying to run `autoreconf`, followed by (after commenting out all of the offenders) `configure` dying:

```
./configure: line 4557: syntax error near unexpected token `X11,'
./configure: line 4557: `  PKG_CHECK_MODULES(X11, x11,'
configure: error: ./configure failed for capdAux
```

At that point, I gave up.

(Note: this is not my machine, and autotools are probably not installed according to the drake instructions.)

**Comment by soonho-tri** [comment]
> Autohell.

sigh...

Let me fix this `-DSUPPORT_ODE=OFF` problem. Then we can use it in drake since we don't use this ODE solver there yet.

**Comment by mwoehlke-kitware** [comment]
Okay... not necessarily high priority though, as it seems to be working for drake (and on Linux); I'm only running into it because I don't have a macOS machine properly set up for drake, which is for some reason tripping over this. (OTOH, it does take ***forever*** to configure CAPD!)

**Comment by soonho-tri** [comment]
Closed by https://github.com/dreal/dreal3/commit/5d43115716f055599fc306e5e23f0a948d0b412b
