### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#35]
(set-logic QF_NRA)
(declare-fun eps () Real)
(declare-fun x1 () Real)
(declare-fun x1p () Real)
(declare-fun x2 () Real)
(declare-fun y () Real)
(assert (<= -10 x1))
(assert (<= x1 10))
(assert (<= -10 x1p))
(assert (<= x1p 10))
(assert (<= -10 x2))
(assert (<= x2 10))
(assert (<= -10 y))
(assert (<= y 10))
(assert (<= -10 eps))
(assert (<= eps 10))
(assert (<= (^ (- x1 x1p) 2) 1))
(assert (
	>=
	(exp (* eps (^ (+ x1 (- x2 y)) 2)))
	(*
	   (exp eps)
	   (exp (* eps (^ (+ x1p (- x2 y) 2))))
	)
   )
)
(check-sat)
(exit)

**Comment by soonhokong** [comment]
Debug build shows me this assertion failure:
```
$ ./dReal test.smt2
Assertion failed: (args->getArity( ) == 2), function mkPow, file /Users/soonhok/work/dreal3/src/opensmt/egraph/EgraphStore.C, line 793.
[1]    16454 abort      ./dReal test.smt2
```

which means that the length of arguments of pow(`^`) should be 2.

**Comment by scungao** [comment]
maybe check that at parsing time

**Comment by scungao** [comment]
btw the web interface is broken. Switch it to dreal3 too?

**Comment by soonhokong** [comment]
Just fixed. It's still dReal2.

**Comment by soonhokong** [comment]
> maybe check that at parsing time

```bash
$ ./dReal sean.smt2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Egraph::mkPow: The number of arguments should be two.
[1]    23593 abort (core dumped)  ./dReal sean.smt2
```
