### ISSUE TITLE
solver bug (QF_NRA)

### ISSUE THREAD

**Issue by dzufferey** [dreal/dreal3#37]
Hi Soonho, Sicun,

dReal returns `unsat` on the following input even though there is a solution.
I using dreal3 compiled from source on the master branch.

```
(set-option :precision 0.1)
(set-logic QF_NRA)
(declare-fun base.dx_dt () Real)
(declare-fun base.q_a () Real)
(declare-fun base.q_a_dt () Real)
(declare-fun base.q_k () Real)
(declare-fun base.q_k_dt () Real)

;a solution
(assert (= base.dx_dt 40.0))
(assert (= base.q_a_dt 0.0))
(assert (= base.q_k_dt 0.0))

;constraints
(assert (= base.q_a 1.0))
(assert (= base.q_k 0.0))
(assert
    (=
        40.0
        (+
            (* 120.0 (^ base.q_k 3.0) base.q_k_dt)
            (* 120.0 (^ base.q_a 2.0) base.q_k base.q_k_dt)
            (* 120.0 base.q_a base.q_a_dt (^ base.q_k 2.0))
            (* (- 1.0) base.dx_dt (^ base.q_k 2.0))
            (* 120.0 (^ base.q_a 3.0) base.q_a_dt)
            (* base.dx_dt (^ base.q_a 2.0))
        )
    )
)

(check-sat)
(exit)
```

**Comment by soonhokong** [comment]
@dzufferey, thanks for the report. I just fixed the problem via 0d28894fc66fdd0b82a5edea0a3787e678d1bf7b.

**Comment by dzufferey** [comment]
@soonhokong Thanks! that was fast.

**Comment by soonhokong** [comment]
FYI, when I completely remove the solution from the formula, it hangs. When I add either 
`(assert (= base.dx_dt 40.0)` or `(assert (= base.q_a_dt 0.0))`, it terminates immediately. Please give some boundaries for variables and let me know if it still takes too much time. I'll take a closer look at them.

Again, thanks for the report. It was very helpful for me as well.
