### ISSUE TITLE
solver bug: unsat on sat formula

### ISSUE THREAD

**Issue by dzufferey** [dreal/dreal3#49]
Hi Soonho, Sicun,

the following file returns unsat, even though it has a solution (set the two variables to 0.0).
```lisp
(set-logic QF_NRA)
(declare-fun base.q_a_dt () Real)
(declare-fun base.dx_dt () Real)
(assert (< base.q_a_dt 10000))
(assert (> base.q_a_dt -10000))
(assert (< base.dx_dt 10000))
(assert (> base.dx_dt -10000))
(assert (<= 0 (+ (* (- 1) 0.9999999999999567 base.dx_dt) (* (- 120) 0.999999999999935 base.q_a_dt)) ))
(check-sat)
(exit)
```

I'm using dreal3 at commit 04c3f2f.
In the more recent version I get a compilation error (unkown 'Json' type). 

Thanks,
Damien

**Comment by soonhokong** [comment]
Thanks for the report. i will fix it asap.

**Comment by soonhokong** [comment]
@scungao,

This one is not related with our theory solver. The UNSAT comes directly from OpenSMT2 side.

Another interesting thing is changing the order of multiplication changes the result:

1. This is UNSAT

    ```lisp
(* (- 1) 0.9999999999999567 base.dx_dt)
    ```
2. This is SAT

    ```lisp
(* (- 1) base.dx_dt 0.9999999999999567)
    ```

I'll check what's going on inside of OpenSMT2, probably simplifier has a bug I guess.

**Comment by scungao** [comment]
I think it has a bug in handling more-than-binary multiplication. Adding parentheses in the first two terms gives correct results.

**Comment by soonhokong** [comment]
The bug is in https://github.com/dreal/dreal3/blob/285f841ca0a029264ba980cd152719c76e91e6fc/src/opensmt/egraph/EgraphStore.C#L996-L1031

In the simplification part of the code, it assumes that there are only two arguments. If the first two arguments are constant (which is the case in @dzufferey's example), we replace the whole multiplication with the multiplication of the first two arguments while ignoring the rest of arguments. For example:

```lisp
(* (- 1) 0.9999999999999567 base.dx_dt)
```

becomes

```lisp
-0.9999999999999567
```

**Comment by soonhokong** [comment]
> I'm using dreal3 at commit 04c3f2f.
> In the more recent version I get a compilation error (unkown 'Json' type).

@dzufferey, this one should be fixed as well. Please check out the latest version and try to compile it. If you still have an issue on building dReal3, please let me know.

**Comment by dzufferey** [comment]
Thanks.

@soonhokong, I still get a compilation error.(I tried a fresh clone of dreal3 repo to be sure I did not mess with the repo.)
here are the relevant parts of the output:
```
[ 62%] Building CXX object contractor/CMakeFiles/contractor.dir/contractor_basic.cpp.o
[ 63%] Building CXX object opensmt/egraph/CMakeFiles/opensmt_egraph.dir/EgraphSolver.C.o
In file included from /home/zufferey/tool/prover/dreal3/src/contractor/contractor.h:25:0,
                 from /home/zufferey/tool/prover/dreal3/src/contractor/contractor_basic.cpp:40:
/home/zufferey/tool/prover/dreal3/src/contractor/contractor_capd4.h:60:5: error: ‘Json’ does not name a type
     Json generate_trace(box b, SMTConfig & config) const;
     ^
In file included from /home/zufferey/tool/prover/dreal3/src/contractor/contractor.h:25:0,
                 from /home/zufferey/tool/prover/dreal3/src/dsolvers/nra_solver.h:36,
                 from /home/zufferey/tool/prover/dreal3/src/opensmt/egraph/EgraphSolver.C:33:
/home/zufferey/tool/prover/dreal3/src/contractor/contractor_capd4.h:60:5: error: ‘Json’ does not name a type
     Json generate_trace(box b, SMTConfig & config) const;

...

contractor/CMakeFiles/contractor.dir/build.make:54: recipe for target 'contractor/CMakeFiles/contractor.dir/contractor_basic.cpp.o' failed
make[2]: *** [contractor/CMakeFiles/contractor.dir/contractor_basic.cpp.o] Error 1
CMakeFiles/Makefile2:2031: recipe for target 'contractor/CMakeFiles/contractor.dir/all' failed
make[1]: *** [contractor/CMakeFiles/contractor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
opensmt/egraph/CMakeFiles/opensmt_egraph.dir/build.make:54: recipe for target 'opensmt/egraph/CMakeFiles/opensmt_egraph.dir/EgraphSolver.C.o' failed
make[2]: *** [opensmt/egraph/CMakeFiles/opensmt_egraph.dir/EgraphSolver.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1367: recipe for target 'opensmt/egraph/CMakeFiles/opensmt_egraph.dir/all' failed
make[1]: *** [opensmt/egraph/CMakeFiles/opensmt_egraph.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
```

**Comment by soonhokong** [comment]
Thanks. Now I see a problem. I can fix it soon.

**Comment by soonhokong** [comment]
@dzufferey, could you try this one https://github.com/dreal/dreal3/commit/388b1b63c07667a01271ecd7b18ed5643feb93e2?

**Comment by dzufferey** [comment]
@soonhokong, no luck I still get the same errors.

Thanks,
Damien

**Comment by soonhokong** [comment]
I see. I will try something else. Thanks for testing it.

On Friday, March 20, 2015, dzufferey <notifications@github.com> wrote:

> @soonhokong <https://github.com/soonhokong>, no luck I still get the same
> errors.
>
> Thanks,
> Damien
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/49#issuecomment-84104178>.
>


-- 
Soonho Kong
soonhok@cs.cmu.edu

**Comment by scungao** [comment]
I can't compile either.

**Comment by soonhokong** [comment]
please try the latest version that I just committed.

**Comment by dzufferey** [comment]
it compiles.

thanks.
