### ISSUE TITLE
Solution format

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#50]
On different files I got different format on the solution returned:
 
SAT with the following box:
                       x1 : [-1.000000000000011, -0.9921874999999891];
                       x2 : [-0, 0.00714233029118137]

SAT with the following box:
                        a : [6, 6.000514005329687]
                        b : [117.5234096698175, 117.5284436413953];

The position of the ";" is not consistent.

**Comment by soonhokong** [comment]
@scungao, could you send me the SMT2 file for the second case? (or paste here, if it's short)

**Comment by soonhokong** [comment]
@scungao, send me an smt2 file plz.

**Comment by soonhokong** [comment]
Please reopen it when you see a similar problem again.
