### ISSUE TITLE
shared lib

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#51]

**Comment by soonhokong** [comment]
need `include` and `lib` in `install` target as well

**Comment by soonhokong** [comment]
In the current version, we're build a library per each subdirectory (for example, `libopensmt_api.a` for `src/opensmt/api`), and link them together to create dReal binary. This approach has been great since it allows us to write CMakeLists.txt in a modular way. However, this is not good when it comes to generate a shared library. We need to first collect all the source files and create a single library such as `libdreal.a` to minimize the number of library that external users need to link.

Reference: http://stackoverflow.com/questions/14104765/is-it-possible-to-bypass-the-new-scope-creation-of-the-add-subdirectory-comman

**Comment by soonhokong** [comment]
We're almost there... To link against dReal, it requires the following extra libraries on which dReal depends:

 - json11
 - glog 
 - gflags 
 - ibex 
 - ClpSolver 
 - Clp 
 - CoinUtils 
 - m
 - prim 
 - capd

**Comment by soonhokong** [comment]
I'm still working on making shared libraries for the following projects:

 - gflags
 - gtest
 - ibex
 - json11
 - prim

**Comment by soonhokong** [comment]
So far, we've used [Dropbox's Json11][1] library, and I think it's time to drop it and move to [another Json][2] library. Why? The new one is

 - header-only library. no need link.
 - It has MIT license which is compatible with GPL (at least GPL software can use MIT, I'm not sure that the other way around).

[1]: https://github.com/dropbox/json11
[2]: https://github.com/nlohmann/json

**Comment by scungao** [comment]
Sounds great!

**Comment by soonhokong** [comment]
For Linux, I've made things working and sent a tar.gz file to @scungao and @zenna. I'm polishing up things so that we can handle 'static' and 'shared' cases.

Another issues is OSX support. It seems that the rules are pretty different from Linux ones, and I couldn't make it there yet.

**Comment by zenna** [comment]
I can't build the executable nor open the shared lib in Julia.  They are probably caused by the same problem.  When building the executable I get:

```
gcc-4.8 -I ./include \
		example.c \
                -o example \
		-Wl,--no-as-needed \
		-Wl,--rpath=`pwd`/lib \
		-L lib \
		-rdynamic \
		-lstdc++ -libex -ldreal -lglog -lgflags -lm -lpthread -lcapd
/usr/bin/ld: warning: libunwind.so.7, needed by lib/libglog.so, not found (try using -rpath or -rpath-link)
lib/libglog.so: undefined reference to `_ULx86_64_step'
lib/libglog.so: undefined reference to `_ULx86_64_get_reg'
lib/libglog.so: undefined reference to `_Ux86_64_getcontext'
lib/libglog.so: undefined reference to `_ULx86_64_init_local'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

Which seems to be the same problem we had before.

When trying to dlopen the shared lib (through Julia) I get:

```
ERROR: could not load module /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so: /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so: undefined symbol: _ZTIN4ibex10SepCtcPairE
 in dlopen at c.jl:19
```

**Comment by zenna** [comment]
Or perhaps they are very different problems.  Could the latter problem be about shared library dependencies?

http://www.gnu.org/software/libtool/manual/html_node/Inter_002dlibrary-dependencies.html

**Comment by soonhokong** [comment]
- The first problem is an easy one and I can send you another zip file tonight.
 - The second one looks different from the first one. Is there an easy way for me to try it (i.e. reproduce the problem)? I have some experience on Julia as well.

**Comment by soonhokong** [comment]
@zenna, could you try the following one?

https://www.dropbox.com/s/81ckebyxzmkzdr4/dreal_c_api_test.tar.gz?dl=0

**Comment by zenna** [comment]
libdreal is missing from from this

**Comment by soonhokong** [comment]
@zenna, I'm sorry. I just updated the file. Could you please try again?

https://dl.dropboxusercontent.com/u/10377018/dreal_c_api_test.tar.gz

**Comment by zenna** [comment]
in julia a first step would be to successfully e run `dlopen("path/to/dreal.so")`

**Comment by zenna** [comment]
Ok the example builds.  The latter problem remains.

```
ERROR: could not load module /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so: /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so: undefined symbol: _ZTIN4ibex10SepCtcPairE
```

**Comment by soonhokong** [comment]
After loading dependent libraries first (libprim, libClp, libibex), I got the following error:

```
ERROR: could not load module /usr0/home/soonhok/tmp/dreal_c_api_test/lib/libdreal.so: /usr0/home/soonhok/tmp/dreal_c_api_test/lib/libdreal.so: undefined symbol: _ZTIN4ibex10SepCtcPairE
 in dlopen at c.jl:19 
```

**Comment by soonhokong** [comment]
OK. I'll check that the library (`libibex.so`) does contain that symbol in it.

**Comment by zenna** [comment]
OK! If we can get `dlopen` to work, I can really start building the library once:

```
ccall( (:opensmt_init, "libdreal"), Void, ())
```

works.

**Comment by soonhokong** [comment]
@zenna, I figured it out.

According to the [Julia documentation for dlopen](http://julia.readthedocs.org/en/latest/stdlib/libdl/?highlight=dlopen#Libdl.dlopen), it says

> An important usage of these flags, on POSIX platforms, is to specify 
> RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL in order for the library’s symbols to be available for 
> usage in other shared libraries, in situations where there are dependencies between shared libraries.

Certainly, we do have dependencies between libraries. Please try the following:

```julia
dlopen("libprim.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
dlopen("libClp.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
dlopen("libibex.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
dlopen("libgflags.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
dlopen("libglog.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
dlopen("libcapd.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
```

and then

```julia
dlopen("libdreal.so", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
```

On my machine (Ubuntu-12.04), I can execute `ccall( (:opensmt_init, "libdreal"), Void, ())` after following the above steps.

**Comment by zenna** [comment]
Thanks

I have a working low level wrap of the C-API in Julia.  Next I'll do a more user friendly interface.

**Comment by soonhokong** [comment]
Excellent!!

On Friday, April 3, 2015, Zenna Tavares <notifications@github.com> wrote:

> Thanks
>
> I have a working low level wrap of the C-API in Julia. Next I'll do a more
> user friendly interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/51#issuecomment-89425282>.
>


-- 
Soonho Kong
soonhok@cs.cmu.edu

**Comment by soonhokong** [comment]
@zenna, I've added an CMake option "BUILD_SHARED_LIB" in https://github.com/dreal/dreal3/commit/5bfed6ed61fd82502343700ca7bd957a7ccb7b97.

When you run `cmake` to build dReal, pass an argument `-DBUILD_SHARED_LIB=ON`. It will create `libdreal.so` and `lib/*.so` libraries.

**Comment by zenna** [comment]
@soonhokong 
1. ibex shared library libibex.so is not being built.

2. I rebuilt dreal from scratch, and used the libibex.so which you sent me before.  Now however I get the following undefined symbol error when dlopening libdreal

```
ERROR: could not load module libdreal.so: /home/zenna/repos/dreal3/build/libdreal.so: undefined symbol: _ZNK4ibex10CellBuffer5printERSo
 in dlopen at ./libdl.jl:33
```

**Comment by soonhokong** [comment]
@zenna, could you try https://dl.dropboxusercontent.com/u/10377018/dreal_c_api_test.tar.gz ?

**Comment by zenna** [comment]
Now I get the `std::logic_error` message

```
Asserting (<= (+ y (* -1 z)) 0)

Checking for consistency: terminate called after throwing an instance of 'std::logic_error'
  what():  unknown literal is asserted

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN9__gnu_cxx27__verbose_terminate_handlerEv at /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (unknown line)
unknown function (ip: -936519626)
unknown function (ip: -936519581)
unknown function (ip: -936519006)
_ZN5dreal10nra_solver9assertLitEP5Enodeb at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN6Egraph9assertLitEP5Enodeb at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN8THandler10assertLitsEv at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN13CoreSMTSolver11checkTheoryEb at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN13CoreSMTSolver6searchEii at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN13CoreSMTSolver5solveERK3vecI3LitEj at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN13SimpSMTSolver5solveERK3vecI3LitEjbb at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN13SimpSMTSolver5solveERK3vecI3LitEbb at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
_ZN14OpenSMTContext8CheckSATEv at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
opensmt_check at /home/zenna/Downloads/dreal_c_api_test/lib/libdreal.so (unknown line)
opensmt_check at /home/zenna/.julia/v0.4/dReal/src/wrap_capi.jl:47
```

Also I did build with `-DSHAREDLIB=ON` and it built all the libraries except libibex.so

**Comment by zenna** [comment]
Any thoughts @soonhokong ?

**Comment by soonhokong** [comment]
@zenna, I was traveling during the weekend ;-) I'll investigate it soon.

**Comment by soonhokong** [comment]
@zenna, you're right. 25bd8edc95b7ea17efda6262dc889d9272f27a6a fixes the problem and now it builds `libibex.so`.

**Comment by soonhokong** [comment]
@zenna, could you try https://dl.dropboxusercontent.com/u/10377018/dreal_shared_lib.tar.gz ? If there is still a problem, I'd like to know how to test dReal.jl.

**Comment by soonhokong** [comment]
@zenna, the dropbox link above is not working anymore. From now on, I'll upload a file with `-shared-lib-tar.gz` at the release page. For example, https://github.com/dreal/dreal3/releases/download/v3.15.04.1/dReal-3.15.04.1-linux-shared-lib.tar.gz is the latest one with shared libraries. Of course, `-DBUILD_SHARED_LIB=ON` should work. If not, please let me know.

**Comment by zenna** [comment]
@soonho I've been building from scratch, but that's a good idea for
distribution

Also, there is no divide (/) in the c api

**Comment by soonhokong** [comment]
> Also, there is no divide (/) in the c api

I will add it.

**Comment by soonhokong** [comment]
@zenna, I just added `mk_div`. See https://github.com/dreal/dreal3/blob/master/src/tests/c_api/example_04.c#L32 for a usage.

**Comment by soonhokong** [comment]
Let me close this one.
