### ISSUE TITLE
support binary min/max

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#70]

**Comment by soonhokong** [comment]
@kquine, @scungao here.

**Comment by soonhokong** [comment]
@kquine, it's there. I added two simple test cases:

 - https://github.com/dreal/dreal3/blob/master/src/tests/nra/min_01.smt2
 - https://github.com/dreal/dreal3/blob/master/src/tests/nra/max_01.smt2

Please feel free to add more testcases.

**Comment by kquine** [comment]
Great! I will try a few more test cases that are related to the airplane
model.

Kyungmin

On Sun, Apr 26, 2015 at 11:08 AM, Soonho Kong <notifications@github.com>
wrote:

> @kquine <https://github.com/kquine>, it's there. I added two simple test
> cases:
>
>    - https://github.com/dreal/dreal3/blob/master/src/tests/nra/min_01.smt2
>    - https://github.com/dreal/dreal3/blob/master/src/tests/nra/max_01.smt2
>
> Please feel free to add more testcases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/70#issuecomment-96397803>.
>



-- 
Kyungmin Bae, Postdoctoral Fellow
School of Computer Science
Carnegie Mellon University

**Comment by scungao** [comment]
Oh this is nice. Is there native support for min and max in IBEX?

**Comment by soonhokong** [comment]
Yes.
