### ISSUE TITLE
Different results from dReal2 and dReal3

### ISSUE THREAD

**Issue by kquine** [dreal/dreal3#72]
For the following same example, dReal2 (ver. 2.15.04) and dReal3 (3.15.04.2) give the different results. dReal2 returns sat, while dReal3 returns unsat. The result should be sat. With the debug option, there is Possible division by zero for dReal3, but not for dReal2. The dReach command is `../bin/dReach -k 1 -l 1 test-air.drh`, where the file name is test-air.drh.

```
#define g           9.80555
#define pi          3.1415926535897931
#define m           20500.0
#define qbw         (13.97 * 30 * 300)
#define qw          (13.97 * 300)
#define vT          111.64
#define c1          -0.770
#define c2          0.02755
#define c3          1.055E-4
#define c4          1.642E-6
#define c8          -0.7336
#define c9          1.587E-5
#define tan(x)      (sin(x) / cos(x))

[-1.5,1.5]  beta;
[-1.5,1.5]  p;
[-1.5,1.5]  r;
[-1.5,1.5]  phi;
[-1.5,1.5]  psi;

[-pi,pi]    xAIL;
[-pi,pi]    rAIL;
[-pi,pi]    gAIL;

[-pi,pi]    xRDR;
[-pi,pi]    rRDR;
[-pi,pi]    gRDR;

[-pi,pi]    gDir;
[0,1]       tau;
[0,1]       time;

{mode 1;
  invt: 
  flow: 
        d/dt[beta]    = qw * (-0.02 * 180 / pi * beta + 0.021 * xAIL / 20 + 0.086 * xRDR / 30) / (m * vT) - r + (vT / g) * cos(beta) * sin(phi);
	d/dt[p]       = (c1 * r + c2 * p) * r * tan(phi) + 
                        qbw * (c3 * (-0.0008 * 180 / pi * beta + 0.05 * xAIL / 20 + 0.013 * xRDR / 30) + 
                               c4 * (0.02 * 180 / pi * beta + -0.01 * xAIL / 20 + -0.04 * xRDR / 30));
	d/dt[r]       = (c8 * p - c2 * r) * r * tan(phi) + 
                        qbw * (c4 * (-0.0008 * 180 / pi * beta + 0.05 * xAIL / 20 + 0.013 * xRDR / 30) + 
                               c9 * (0.02 * 180 / pi * beta + -0.01 * xAIL / 20 + -0.04 * xRDR / 30));
	d/dt[phi]     = p;
	d/dt[psi]     = (g / vT) * tan(phi);

        d/dt[xAIL]    = rAIL;
        d/dt[rAIL]    = 0;
	d/dt[gAIL]    = 0;

        d/dt[xRDR]    = rRDR;
        d/dt[rRDR]    = 0;
	d/dt[gRDR]    = 0;

	d/dt[gDir]    = 0;
        d/dt[tau]     = 1;
  jump: 
        (and (tau = 1)) ==> 
        @1 (and (beta' = beta) (p' = p) (r' = r) (phi' = phi) (psi' = psi) 
                (xAIL' = xAIL) (rAIL' = rAIL) (gAIL' = gAIL)
                (xRDR' = xRDR) (rRDR' = rRDR) (gRDR' = gRDR)
                (gDir' = gDir) (tau' = 0));
}

init: @1 (and (beta = 0)   (p = 0)       (r = 0)      (phi = 0)    (psi = 0)  
              (xAIL = 0)   (rAIL = 0.25) (gAIL = 0) 
              (xRDR = 0)   (rRDR = 0.5)  (gRDR = 0) 
              (gDir = 0.5) (tau = 0));
goal: @1 true; 
```

**Comment by soonhokong** [comment]
I think this one comes from the same problem with #73. Now, dReal3 gives delta-SAT with the following visualization:

![screen shot 2015-04-27 at 11 32 40 am](https://cloud.githubusercontent.com/assets/403281/7351119/41019024-ecd1-11e4-9af0-3c2afa83647a.png)

I got the following visualization from dReal2:
![screen shot 2015-04-27 at 11 33 07 am](https://cloud.githubusercontent.com/assets/403281/7351150/76c1fa5a-ecd1-11e4-9b8b-8b5b0d95838b.png)

For me, the only difference is that dReal3 does not show the constants in the flow. @kquine, can you confirm that this issue is resolved?

**Comment by kquine** [comment]
Yes, the problem seems to be also caused by the same bug.

On Mon, Apr 27, 2015 at 11:36 AM, Soonho Kong <notifications@github.com>
wrote:

> I think this one comes from the same problem with #73
> <https://github.com/dreal/dreal3/issues/73>. Now, dReal3 gives delta-SAT
> with the following visualization:
>
> [image: screen shot 2015-04-27 at 11 32 40 am]
> <https://cloud.githubusercontent.com/assets/403281/7351119/41019024-ecd1-11e4-9af0-3c2afa83647a.png>
>
> I got the following visualization from dReal2:
> [image: screen shot 2015-04-27 at 11 33 07 am]
> <https://cloud.githubusercontent.com/assets/403281/7351150/76c1fa5a-ecd1-11e4-9b8b-8b5b0d95838b.png>
>
> For me, the only difference is that dReal3 does not show the constants in
> the flow. @kquine <https://github.com/kquine>, can you confirm that this
> issue is resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreal/dreal3/issues/72#issuecomment-96713236>.
>



-- 
Kyungmin Bae, Postdoctoral Fellow
School of Computer Science
Carnegie Mellon University
