### ISSUE TITLE
non-determinism in solving

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#85]
I found that solving `tests/nra/hansen_hockey.smt2` shows some non-deterministic behaviors.

Running `dReal src/tests/nra/hansen_hockey.smt2 --stat` multiple times give different stat information from time to time:

```
$ ./dReal ../../src/tests/nra/hansen_hockey.smt2 --stat
unsat
Number of Complete   Check = 0
Number of Incomplete Check = 184
Number of Assert           = 580
Number of Push             = 585
Number of Pop              = 585

$ ./dReal ../../src/tests/nra/hansen_hockey.smt2 --stat
unsat
Number of Complete   Check = 0
Number of Incomplete Check = 205
Number of Assert           = 610
Number of Push             = 615
Number of Pop              = 615
```

**Comment by pzuliani** [comment]
I'm using dReal version 3.15.04.2 (commit fae153a4995e) and it seems I cannot get different stats than these ..

```
$  ./dReal ../src/tests/nra/hansen_hockey.smt2 --stat
unsat
Number of Complete   Check = 0
Number of Incomplete Check = 219
Number of Assert           = 712
Number of Push             = 717
Number of Pop              = 717
```

**Comment by soonhokong** [comment]
@pzuliani, thanks for checking this. On my Linux box, I also have a consistent number. But still a release build and a debug build give different numbers, which is strange:

DEBUG (Ubuntu-12.04 / gcc-4.9)
```
Number of Complete   Check = 0
Number of Incomplete Check = 209
Number of Assert           = 661
Number of Push             = 667
Number of Pop              = 667
```

RELEASE (Ubuntu-12.04 / gcc-4.9)
```
Number of Complete   Check = 0
Number of Incomplete Check = 240
Number of Assert           = 776
Number of Push             = 782
Number of Pop              = 782
```

Also, using clang++-3.4.2 instead of g++-4.9.2 gives a different number:

RELEASE (Ubuntu-12.04 / clang++-3.4.2)
```
Number of Complete   Check = 0
Number of Incomplete Check = 183
Number of Assert           = 579
Number of Push             = 585
Number of Pop              = 585
```

**Comment by pzuliani** [comment]
On my Ubuntu 14.04.2 the stats of the release build are the same with either clang++3.5 or g++4.9 ...

**Comment by soonhokong** [comment]
OK.. I'll get some vitamin C pills and a cup of coffee and do sanity check for myself first...

**Comment by soonhokong** [comment]
@nnarodytska and I were investigating this issue yesterday briefly. We observed that it came from SAT-level. Here are trace of two runs of `dReal src/tests/hansen_hockey.smt2` (to get more debugging output, I've changed verbosity level at [SMTConfig.C](https://github.com/dreal/dreal3/blob/master/src/opensmt/smtsolvers/SMTConfig.C#L66):

Run 1
```
...
# Egraph::Asserting Literal:      (= distance_2 distance_3)
nra_solver::assertLit: (= distance_2 distance_3), reason: false, polarity: 1, deduced: false, getDeduced: 0, getIndex: -2, level: 48, ded.size = 1
```

Run 2
```
...
# Egraph::Asserting Literal:      (= px_2 px_3)
nra_solver::assertLit: (= px_2 px_3), reason: false, polarity: 1, deduced: false, getDeduced: 0, getIndex: -2, level: 48, ded.size = 1
```

@nnarodytska, could you check what's going on at SAT level when you have some time? Initially, I thought that there is some comparisons based on pointer values in the code. But you thought that it should not be the case.. At least, I'm sure that our theory solver does not use any randomization.

**Comment by scungao** [comment]
There are numerical weights that the solver uses to prioritize certain
decisions. Maybe some tricky floating point behavior is involved because of
that?

**Comment by nnarodytska** [comment]
Hi Soonho, 

I was not able to reproduce the issue so far. I have the same stats in all runs.

nina

**Comment by soonhokong** [comment]
@nnarodytska, could you compare the numbers from a debug build and a release build?

**Comment by nnarodytska** [comment]
@soonhokong The numbers are the same in debug and release modes. I am working with your lastest version from: git@github.com:soonhokong/dreal3

**Comment by soonhokong** [comment]
I see. Thank you for checking it. Let me close this one for now.

**Comment by soonhokong** [comment]
@nnarodytska, problem solved. It's all because of nra_solver. :-(

**Comment by soonhokong** [comment]
When we generate an explanation (which is a vector of Enode). I use STL set to make sure that there is a single occurrence of an element in the vector. By default, STL set uses native `<` operator to order the elements. In this case, the element's type is `Enode *`. So it uses pointer address to give an order between two elements, which can change over runs.

**Comment by scungao** [comment]
Good to know..

**Comment by nnarodytska** [comment]
Cool, a learnt clause was our suspect :). Is it deterministic now?

**Comment by nnarodytska** [comment]
@soonhokong 

Could you please push the last fix (that fixes the non-deterministic behaviour)? I was running dReal with valgrind. I get different stats with and without valgrind in the debug mode.

**Comment by soonhokong** [comment]
@nnarodytska, I'm fixing it now. I'll ping you when I'm done.

**Comment by nnarodytska** [comment]
Thanks!

**Comment by soonhokong** [comment]
@nnarodytska, it's there.

**Comment by nnarodytska** [comment]
Thanks, it works for me. I get the same stats on the hansen_hockey.smt2 benchmark in different modes.

**Comment by soonhokong** [comment]
Great!
