### ISSUE TITLE
bug in worklist fixpoint alg

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#86]
There is still a case where [worklist fixpoint alg](https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_basic.cpp#L216-L265) terminates prematurely, that is, it stops when it should continue.

I found this while working on adding `--theory_propagation` option. When the option is on, we do the followings:

 1. Theory check with asserted literals -- `l_1`, ..., `l_n`
 2. If the result is SAT. Check deductions. If there is any, assert them. 
 3. Let's assume that  now we have `l_1`, ... , `l_n`, `l_n+1`, ... , `l_m` on the stack where `l_n+1`, ..., `l_m` are the deduced literals by `l_1`, ..., `l_n`.
 4. Theory check with asserted literals -- `l_1`, ... , `l_n`, `l_n+1`, ... , `l_m`
 5. We should have SAT again here, because `l_n+1`, ... , `l_m` are entailed by `l_1`, ... , `l_n`

Using the current [worklist fixpoint alg](https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_basic.cpp#L216-L265) implementation, we have a case where step 5 fails, that is it gives us UNSAT. I checked that using [naive fixpoint alg](https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_basic.cpp#L195-L214) doesn't generate this problem, at least for our benchmark.

I'll get back to this after handling some ODE issues.

---

@nnarodytska, I have a question about the above five steps (which are in [CoreSMTSolver::checkTheory](https://github.com/dreal/dreal3/blob/master/src/opensmt/smtsolvers/Theory.C#L46-L76)).

 - Isn't it the case that step 5 is actually unnecessary? It helped us find the problem but I think it should always be SAT for our cases. In the code, [it mentions that](https://github.com/dreal/dreal3/blob/master/src/opensmt/smtsolvers/Theory.C#L60-L65) `This case can happen only during DTC`. I'm not sure that this is relevant to us.

 - May be what we need is to call Boolean propagation after step 4, possibly assert more literals, and call theory-check. What do you think?

**Comment by nnarodytska** [comment]
@soonhokong

1. I think it is important to verify that step 5 holds.  We should not get additional propagation for the same set of constraints after a fixpoint was reached. This is one of the invariants of the algorithm. Do you agree? 

2. We will call Boolean propagation at the next step (after we return from checkTheory).


Could you please let me know a benchmark name where worklist fixpoint alg terminates prematurely?

**Comment by soonhokong** [comment]
> I think it is important to verify that step 5 holds. We should not get additional propagation for the same set of constraints after a fixpoint was reached. This is one of the invariants of the algorithm. Do you agree?

@nnarodytska, let's keep it as we discussed.

> Could you please let me know a benchmark(s) name where worklist fixpoint alg terminates prematurely?

It's our favorite example, `hansen_hockey.smt2`. You can test it by changing https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_basic.cpp#L180-L186.
