### ISSUE TITLE
add testcases for --short_sat option

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal3#87]
@nnarodytska, I'll add it in an hour and push to the blessed repo.

**Comment by nnarodytska** [comment]
@soonhokong Should I just run "ctest" to test short_sat?

**Comment by soonhokong** [comment]
I already talked to Nina about it. Just for the record, I mentioned `-L` (label) and `-R` (test name) options in ctest. Here is a reference: http://www.cmake.org/cmake/help/v3.0/manual/ctest.1.html.
